name: smart_glove
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:

  cloud_firestore: ^5.5.1
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1
  firebase_database: ^11.2.0
  flutter:
    sdk: flutter

  flutter_blue_plus: ^1.34.5


  flutter_tts: ^4.2.0
  permission_handler: ^11.3.1
  speech_to_text: ^7.0.0
  stacked: ^3.4.3
  stacked_services: ^1.1.0




dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3



flutter:
  uses-material-design: true

